config/routes.rb
Rails.application.routes.draw do
  
  resources :books do
    member do
      get 'details'
    end
  end

  resources :lecturas, only: [:new, :create, :destroy, :update] do
    member do
      get 'details'
    end
  end
  resources :notas
  resources :logs_lecturas, only: [:index, :new, :create, :destroy]
  root 'landing_page#index'

  get 'signIn', to: "usuarios#signIn"
  post 'signIn', to: "usuarios#crear", as: "crear"
  get 'logIn', to: "sessions#logIn"
  post 'logIn', to: "sessions#crear", as: "log_in"
  delete 'logOut', to: "sessions#logOut", as: "log_out"
  get 'library', to: 'lecturas#library'
  get 'lecture_search', to: 'lecturas#search'
  get 'book_search', to: 'books#search'

  get 'review_search', to: 'reviews#search', as: 'reviews_search'
  get 'create_rating', to: 'books#create_rating', as: 'create_rating'
  post 'create_rating', to: 'reviews#create', as: 'create_review'
  get 'reset_rating', to: 'books#reset_rating', as: 'reset_rating'

  
  resources :amigos, only: [:view, :create, :update, :destroy]
  #get 'amigos',to:'amigos#view'
  get 'amigos', to: 'amigos#view'
  get 'amigos/restricted_action', to: 'amigos#restricted_action'
  get 'amigos/public_action', to: 'amigos#public_action'
  get 'amigos/view/:id', to: 'amigos#view', as: 'view_amigo'


  get 'notificaciones', to: 'notificaciones#view'

  # Rutas RESTful para usuarios (incluyendo edit y update)
  resources :usuarios, only: [:edit, :update]

  get 'profile', to:'usuarios#profile', as:'profile'
  get 'edit_user', to:'usuarios#edit_user', as:'edit_user'
  post 'edit_user', to:'usuarios#edit_user'

  get 'users_search', to: 'usuarios#search'

  get 'reviews', to: "reviews#reviews"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/amigos_controller.rb
class AmigosController < ApplicationController
  before_action :require_user, only: [ :create, :update, :destroy] # Asegura que el usuario esté autenticado para estas acciones
  before_action :set_usuario, only: [:view]


  def view
    if current_user
      #@amigos = current_user.amigos + current_user.inverse_amigos
      @amigos = current_user.amigos
      if @amigos.empty?
        flash.now[:alert] = "No tienes amigos añadidos."
      end
    else
      flash[:alert] = "Debes iniciar sesión para ver esta página."
    end
  end

  def create
    @amigo = Usuario.find(params[:amigo_id])
    @amistad = current_user.amistades.build(amigo: @amigo, estado: 'pendiente')

    if @amistad.save
      flash[:notice] = "Solicitud de amistad enviada."
      redirect_to profile_path(@amigo)
    else
      flash[:alert] = "No se pudo enviar la solicitud de amistad."
      redirect_to usuarios_path
    end
  end

  def update
    @amistad = Amistad.find(params[:id])
    if @amistad.update(estado: params[:estado])
      flash[:notice] = "Solicitud de amistad actualizada."
      redirect_to profile_path(current_user)
    else
      flash[:alert] = "No se pudo actualizar la solicitud de amistad."
      redirect_to profile_path(current_user)
    end
  end

  def destroy
    @amistad = Amistad.find(params[:id])
    @amistad.destroy
    flash[:notice] = "Amistad eliminada."
    redirect_to profile_path(current_user)
  end

  private

  def set_usuario
    @usuario = Usuario.find(params[:id]) if params[:id]
  end
end

app/helpers/amigos_helper.rb
module AmigosHelper
end

app/views/amigos/view.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Rincon literario libreria</title>

    <!-- Custom fonts for this template-->
        <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <style>
    .inline-item {
        display: block ruby;
      }
      
    </style>

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-primary sidebar accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= root_path()%>">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fa-solid fa-book-open"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Rincón Literario</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Biblioteca -->
            <li class="nav-item active">
                <a class="nav-link" href="<%= library_path%>">
                    <i class="fa-solid fa-book"></i>
                    <span>Biblioteca</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Buscar -->
            <li class="nav-item">
                <a class="nav-link" href="<%= book_search_path %>">
                    <i class="fa-solid fa-magnifying-glass"></i>
                    <span>Buscar</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Reseñas -->
            <li class="nav-item">
                <a class="nav-link" href="<%= reviews_path %>">
                    <i class="fa-solid fa-star"></i>
                    <span>Reseñas</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Amigos -->
            <li class="nav-item">
                <a class="nav-link" href="<%=amigos_path %>
                ">
                    <i class="fa-solid fa-user-group"></i>
                    <span>Amigos</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Notificaciones -->
            <li class="nav-item">
                <a class="nav-link" href="<%=notificaciones_path %>">
                    <i class="fa-solid fa-bell"></i>
                    <span>Notificaciones</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light topbar mb-4 static-top shadow">
              <h1 class="h3 mb-0  text-gray-800 ">Mis Amigos</h1>
              <!-- Topbar Navbar -->
              <ul class="navbar-nav ml-auto">
                  <div class="topbar-divider d-none d-sm-block"></div>
                  <!-- Nav Item - User Information -->
                  <% if logged_in?%>
                      <li class="nav-item dropdown no-arrow">
                          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%=current_user.username%></span>
                              <i class="fa-solid fa-user"></i>
                          </a>
                          <!-- Dropdown - User Information -->
                          <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                              aria-labelledby="userDropdown">
                              <a class="dropdown-item" >
                                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                  Profile
                              </a>
                              <a class="dropdown-item" href="edit_user">
                                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                  Settings
                              </a>
                              <a class="dropdown-item" href="#">
                                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                  Activity Log
                              </a>
                              <div class="dropdown-divider"></div>
                              <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                  Logout
                              </a>
                          </div>
                      </li>
                  <% else %>
                      <li class="nav-item dropdown no-arrow">
                          <a class="nav-link dropdown-toggle" href="logIn">
                              <span class="mr-2 d-none d-lg-inline text-gray-600 small">Log in</span>
                              <i class="fa-solid fa-user"></i>
                          </a>
                      </li>
                  <% end %>
              </ul>
            </nav>
            <!-- End of Topbar -->
  
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    
                    <% if flash[:alert] == "Debes iniciar sesión para ver esta página." %>
                        <div class="alert alert-warning">
                            <%= flash[:alert] %>
                            <%= link_to 'Iniciar sesión', logIn_path, class: 'btn btn-primary' %>
                        </div>
                        <% elsif flash[:alert] %>
                        <div class="alert alert-warning">
                            <%= flash[:alert] %>
                        </div>
                    <% end %>


                    <%= yield %>
                    <!-- Content Row -->
                    <div class="row">
                   
                        <% if current_user %>
                            
                            <% if @amigos.any? %>
                                <ul>
                                <% @amigos.each do |amigo| %>
                                    <li class="inline-item">
                                    <%= link_to profile_path(id: amigo.id), class: 'custom-link' do %>
                                        <strong><%= amigo.username.upcase %></strong>
                                      <% end %>
                                      
                                        
                                        <%= form_with(url: amigo_path(current_user.amistades.find_by(amigo: amigo)), method: :delete, local: true, class: 'd-inline') do |f| %>
                                            <%= f.submit 'Eliminar amistad', class: 'btn btn-primary' %>
                                        <% end %>

                                    </li>
                                <% end %>
                                </ul>
                            
                                
                            <% end %>
                            <% else %>
                            <p>Debes iniciar sesión para ver esta página.</p>
                        <% end %>

                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container mt-3 mb-3" style="height: 10px;">
                    <div class="copyright text-center mt-3 mb-3">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">¿Deséas cerrar tu sesión?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                    <%= button_to "Log out", log_out_path, method: :delete, class: "btn btn-primary" %>
                </div>
            </div>
        </div>
    </div>

    
    <!-- Core plugin JavaScript
    <%= javascript_include_tag 'jquery.easing.min' %>-->

    <!-- Bootstrap core JavaScript-->
    <%= javascript_include_tag 'jquery.min.js' %>
    <%= javascript_include_tag 'bootstrap.bundle.min' %>
    
    <!-- Custom scripts for all pages-->
    <%= javascript_include_tag 'sb-admin-2.min' %>

</body>

</html>