config/routes.rb
Rails.application.routes.draw do
  
  resources :books do
    member do
      get 'details'
    end
  end

  resources :lecturas, only: [:new, :create, :destroy, :update] do
    member do
      get 'details'
    end
  end
  resources :notas
  resources :logs_lecturas, only: [:index, :new, :create, :destroy]
  root 'landing_page#index'

  get 'signIn', to: "usuarios#signIn"
  post 'signIn', to: "usuarios#crear", as: "crear"
  get 'logIn', to: "sessions#logIn"
  post 'logIn', to: "sessions#crear", as: "log_in"
  delete 'logOut', to: "sessions#logOut", as: "log_out"
  get 'library', to: 'lecturas#library'
  get 'lecture_search', to: 'lecturas#search'
  get 'book_search', to: 'books#search'

  get 'review_search', to: 'reviews#search', as: 'reviews_search'
  get 'create_rating', to: 'books#create_rating', as: 'create_rating'
  post 'create_rating', to: 'reviews#create', as: 'create_review'
  get 'reset_rating', to: 'books#reset_rating', as: 'reset_rating'

  
  resources :amigos, only: [:view, :create, :update, :destroy]
  #get 'amigos',to:'amigos#view'
  get 'amigos', to: 'amigos#view'
  get 'amigos/restricted_action', to: 'amigos#restricted_action'
  get 'amigos/public_action', to: 'amigos#public_action'
  get 'amigos/view/:id', to: 'amigos#view', as: 'view_amigo'


  get 'notificaciones', to: 'notificaciones#view'

  # Rutas RESTful para usuarios (incluyendo edit y update)
  resources :usuarios, only: [:edit, :update]

  get 'profile', to:'usuarios#profile', as:'profile'
  get 'edit_user', to:'usuarios#edit_user', as:'edit_user'
  post 'edit_user', to:'usuarios#edit_user'

  get 'users_search', to: 'usuarios#search'

  get 'reviews', to: "reviews#reviews"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def reviews
        @reviews = Review.all.order(created_at: :desc)
    end

    def create
        @usuarioActual = Usuario.find(session[:usuario_id])
        if (@usuarioActual.reviews.find_by(libro_id: review_params[:libro_id]))
            flash[:danger] = "Ya creaste una review para este libro"
        else    
            @review = @usuarioActual.reviews.create(review_params)
            if (@review.save)
                flash[:success] = "Se creo exitosamente la review"
            else
                flash[:danger] = @review.errors.full_messages[0]
            end
        end
        goBack
    end

    def search
        @search_query = params[:search]
        
        if params[:search].present?
            @ids_posibles = get_books_id(@search_query)
            @reviews = Review.where(libro_id: @ids_posibles)
        else
            @reviews = []
        end
        render :reviews
    end

    def get_books_id(book)
        @lista = []
        api_service = ExternalApiService.new()
        params = {
            search: book,
            maxResults: 20,
            pageNumber: 0
        }
        begin
          @data = api_service.fetch_books2(params)
          api_service.fetch_books2(params)
        rescue => e
          @error = e.message
          @data = nil
        end
        for @libro in @data['items']
            @lista.append(@libro['id'])
        end
        @lista
    end

    def reviewsPerfil
    end

    def review_params
        params.require(:review).permit(:libro_id, :comentario, :puntuacion)
                                .merge(fecha: Date.today)
                                .merge(puntuacion: params[:puntuacion].to_i)
    end

    def goBack
        previous_url = request.referrer
        redirect_to previous_url if previous_url.present?
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_create_rating_modal.html.erb
<head>
    <%= stylesheet_link_tag 'create_rating' %>
</head>

<body>
  <div class="modal fade" id="createRatingModal" tabindex="-1" role="dialog" open="false" aria-labelledby="createRatingModalLabel" aria-hidden="true">
    <div class="modal-dialog">
    <div class="modal-content">
    <div class="modal-header">
    <h5 class="modal-title" id="createRatingModalLabel">Crear Calificación</h5>
    <a href="<%= reset_rating_path%>" class="btn-close" aria-label="Close"><i class="fa-solid fa-xmark"></i></a>
    </div>
    <div class="modal-body">
        <%= form_with(model: Review, url: create_review_path, local: true) do |form| %>
          <div class="espaciado">
          <% 1.upto(5) do |value| %>
            <label for="star_<%= value %>" class="form-check-label">
            <% if @rating && value <= @rating %>
                <i class="fa-solid fa-star text-success"></i>
            <% else %>
                <i class="fa-regular fa-star text-success"></i>
            <% end %>
            <%= radio_button_tag :puntuacion, 
            value, 
            class: "form-check-input d-none",
                checked: @rating == value,
                id: "star_#{value}" %>
                </label>
            <% end %>
          </div>
          <div class="form-group">
              <%= form.text_field :libro_id, 
              value: book_id,
              class: "d-none" %>
              <%= form.text_area :comentario, 
              class: "form-control form-control",
              placeholder: "Comentario" %>
          </div>
        <%= form.submit "Publicar review", 
        class: "btn btn-secondary btn-block" %>
                                          
        <% end %>
        </div>
      </div>
    </div>
  </div>

    
  <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js' %>
  <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js' %>
</body>

app/views/reviews/reviews.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Rincon literario reviews</title>

    <!-- Custom fonts for this template-->
        <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <%= stylesheet_link_tag 'reviews' %>
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-primary sidebar accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= root_path()%>">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fa-solid fa-book-open"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Rincón Literario</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Biblioteca -->
            <li class="nav-item">
                <a class="nav-link" href="<%= library_path%>">
                    <i class="fa-solid fa-book"></i>
                    <span>Biblioteca</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Buscar -->
            <li class="nav-item">
                <a class="nav-link" href="<%= book_search_path %>">
                    <i class="fa-solid fa-magnifying-glass"></i>
                    <span>Buscar</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Reseñas -->
            <li class="nav-item active">
                <a class="nav-link" href="<%= reviews_path %>">
                    <i class="fa-solid fa-star"></i>
                    <span>Reseñas</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Amigos -->
            <li class="nav-item">
                <a class="nav-link" href="<%= amigos_path %>">
                    <i class="fa-solid fa-user-group"></i>
                    <span>Amigos</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Notificaciones -->
            <li class="nav-item">
                <a class="nav-link" href="<%= notificaciones_path %>">
                    <i class="fa-solid fa-bell"></i>
                    <span>Notificaciones</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <%= form_with url: reviews_search_path, method: :get, local: true do %>
                        <div class="input-group">
                            <%= text_field_tag :search, @search_query, class: "form-control bg-light border-0 small", placeholder: "Buscar por libro..." %>
                            <div class="input-group-append">
                                <%= submit_tag "Buscar", class: "btn btn-primary" %>
                            </div>
                        </div>
                    <% end %>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <% if logged_in?%>
                            <li class="nav-item dropdown no-arrow">
                                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%=current_user.username%></span>
                                    <i class="fa-solid fa-user"></i>
                                </a>
                                <!-- Dropdown - User Information -->
                                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                    aria-labelledby="userDropdown">
                                    <a class="dropdown-item" href="<%= profile_path%>">
                                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Profile
                                    </a>
                                    <a class="dropdown-item" href="<%= edit_user_path%>">
                                        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Settings
                                    </a>
                                    <a class="dropdown-item" href="#">
                                        <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Activity Log
                                    </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Logout
                                    </a>
                                </div>
                            </li>
                        <% else %>
                            <li class="nav-item dropdown no-arrow">
                                <a class="nav-link dropdown-toggle" href="logIn">
                                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">Log in</span>
                                    <i class="fa-solid fa-user"></i>
                                </a>
                            </li>
                        <% end %>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 ">Reviews</h1>
                    </div>

                    <!-- Content Row -->
                    <div class="contenedor">
                        <% if !@reviews.empty?%>
                            <% @reviews.each do |review| %>
                                <div class="card shadow">
                                <!-- Card Header - Dropdown -->
                                <div class="card-header fila">
                                    <div>
                                    <% 1.upto(5) do |value| %>
                                        <% if value <= review.puntuacion %>
                                            <i class="fa-solid fa-star text-success margin-top"></i>
                                        <% else %>
                                            <i class="fa-regular fa-star text-success margin-top"></i>
                                        <% end %>
                                    <% end %>
                                    </div>
                                    <h4 class="margen font-weight-bold"> | <%=review.titulo_libro %></h4>
                                </div>
                                <div class="card-body">
                                    <h4 class="font-weight-bold"> <%= review.creador %> </h4>
                                    <h5 class="mb-0"><%= review.comentario %></h5>
                                    <h6 class="mb-0 "><%= review.fecha.to_formatted_s(:long) %></h6>
                                </div>
                            </div>
                            <% end %>
                        <% else %>
                        <p> No hay reviews. </p>
                        <% end %>

                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container mt-3 mb-3" style="height: 10px;">
                    <div class="copyright text-center mt-3 mb-3">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">¿Deséas cerrar tu sesión?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                    <%= button_to "Log out", log_out_path, method: :delete, class: "btn btn-primary" %>
                </div>
            </div>
        </div>
    </div>

    
    <!-- Core plugin JavaScript
    <%= javascript_include_tag 'jquery.easing.min' %>-->

    <!-- Bootstrap core JavaScript-->
    <%= javascript_include_tag 'jquery.min.js' %>
    <%= javascript_include_tag 'bootstrap.bundle.min' %>
    
    <!-- Custom scripts for all pages-->
    <%= javascript_include_tag 'sb-admin-2.min' %>

</body>

</html>